export const TYPE_BUDGET = 'BUDGET';
export const TYPE_DEFAULT_BUDGET = 'DEFAULT_BUDGET';
export const TYPE_INCOME = 'INCOME';
export const TYPE_SAVINGS = 'SAVINGS';
export const TYPE_TRANSACTION = 'TRANSACTION';

export const ALL_TRANSACTION_TYPES = [TYPE_BUDGET, TYPE_DEFAULT_BUDGET, TYPE_INCOME, TYPE_SAVINGS, TYPE_TRANSACTION];

export const SPEND_TRANSACTION_TYPES = [TYPE_BUDGET, TYPE_TRANSACTION];

export const DEFAULT_BUDGET_DATE = "1970-01-01";